name: Build
on:
  pull_request:
    branches: [ master, develop, release/*, hotfix/* ]
    
jobs:
    runs-on: ubuntu-latest    
    name: Run MSBuild

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore